services:
  postgres-db:
    image: postgres:17   # Use the desired version of PostgreSQL
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres        # Replace with your desired username
      POSTGRES_PASSWORD: luffyD1998!  # Replace with your desired password
      POSTGRES_DB: vclips_user_info       # Replace with your desired database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists data even after container restarts

volumes:
  postgres_data:
